name: 'Twilio SMS'
author: 'Twilio Labs'
description: 'Send an SMS from GitHub Actions using Twilio Programmable SMS'
inputs:
  FROM_PHONE_NUMBER:
    description: 'Phone number in your Twilio account to send the SMS from'
    required: true
  TO_PHONE_NUMBER:
    description: 'Phone number to send the SMS to'
    required: true
  message:
    description: 'The message you want to send'
    required: true
  TWILIO_ACCOUNT_SID:
    description: 'A Twilio Account SID.'
    required: true
  TWILIO_AUTH_TOKEN:
    description: 'A Twilio Auth Token.'
    required: true
outputs:
  messageSid:
    description: 'The Twilio Message SID'
runs:
  using: 'node16'
  main: 'dist/main.js'
branding:
  color: 'red'
  icon: 'message-circle'
