name: 'Twilio SMS'
author: 'Twilio Labs'
description: 'Send an SMS from GitHub Actions using Twilio Programmable SMS'
inputs:
  fromPhoneNumber:
    description: 'Phone number in your Twilio account to send the SMS from'
    required: true
  toPhoneNumber:
    description: 'Phone number to send the SMS to'
    required: true
  message:
    description: 'The message you want to send'
    required: true
  TWILIO_ACCOUNT_SID:
    description: 'A Twilio Account SID. Can alternatively be stored in environment'
    required: true
  TWILIO_API_KEY:
    description: 'A Twilio API Key. Can alternatively be stored in environment'
    required: true
  TWILIO_API_SECRET:
    description: 'A Twilio API Secret. Can alternatively be stored in environment'
    required: true
outputs:
  messageSid:
    description: 'The Twilio Message SID'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'red'
  icon: 'message-circle'
