name: Test
on:
  [pull_request]
jobs:
  check:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
    - name: npm
      run: |
        npm run dev
        npm run clean
